# Generated by Django 3.1.2 on 2020-10-17 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('attached_image', models.ImageField(blank=True, null=True, upload_to=news.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='ReadNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_news_news_id', to='news.news')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_news_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
