# Generated by Django 3.1.2 on 2020-10-17 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gears', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purpose_type', models.IntegerField(choices=[(1, '登山'), (2, '登山（積雪期）'), (3, '登山（残雪期）'), (4, 'ハイキング'), (5, 'トレイルランニング'), (6, 'クライミング'), (7, 'アルパインクライミング'), (8, '沢登り'), (9, 'BCスキー'), (10, 'BCスノーボード'), (11, 'その他')])),
                ('has_rain_wear', models.BooleanField(default=True)),
                ('has_winter_clothing', models.BooleanField(default=True)),
                ('has_map', models.BooleanField(default=True)),
                ('has_compass', models.BooleanField(default=True)),
                ('has_headlamp', models.BooleanField(default=True)),
                ('has_mobile_phone', models.BooleanField(default=True)),
                ('has_spare_battery', models.BooleanField(default=True)),
                ('has_first_aid_kit', models.BooleanField(default=True)),
                ('has_emergency_tent', models.BooleanField(default=True)),
                ('has_transceiver', models.BooleanField(default=False)),
                ('call_sign', models.CharField(blank=True, max_length=50, null=True)),
                ('has_radio', models.BooleanField(default=False)),
                ('has_tent', models.BooleanField(default=False)),
                ('has_sleeping_bag', models.BooleanField(default=False)),
                ('has_stove', models.BooleanField(default=False)),
                ('has_helmet', models.BooleanField(default=False)),
                ('has_climbing_rope', models.BooleanField(default=False)),
                ('has_climbing_gear', models.BooleanField(default=False)),
                ('has_crampons', models.BooleanField(default=False)),
                ('has_ice_axe', models.BooleanField(default=False)),
                ('has_shovel', models.BooleanField(default=False)),
                ('has_beacon', models.BooleanField(default=False)),
                ('has_probe', models.BooleanField(default=False)),
                ('has_snow_saw', models.BooleanField(default=False)),
                ('has_riding_gear', models.BooleanField(default=False)),
                ('riding_type', models.IntegerField(blank=True, choices=[(1, 'スキー'), (2, 'スノーボード'), (3, 'スプリットボード'), (4, '雪板'), (5, 'その他')], null=True)),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('updated_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_updated_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_date', models.DateField()),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_plan_id', to='plans.plan')),
                ('updated_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_updated_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanRouteDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('is_staying', models.BooleanField(default=False)),
                ('sort_index', models.IntegerField()),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_detail_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('plan_route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_detail_plan_route_id', to='plans.planroute')),
                ('updated_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_detail_updated_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanMountain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('sort_index', models.IntegerField()),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_mountain_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_mountain_plan_id', to='plans.plan')),
                ('updated_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_mountain_updated_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=8)),
                ('prefecture', models.IntegerField(choices=[(1, '北海道'), (2, '青森県'), (3, '岩手県'), (4, '宮城県'), (5, '秋田県'), (6, '山形県'), (7, '福島県'), (8, '茨城県'), (9, '栃木県'), (10, '群馬県'), (11, '埼玉県'), (12, '千葉県'), (13, '東京都'), (14, '神奈川県'), (15, '新潟県'), (16, '富山県'), (17, '石川県'), (18, '福井県'), (19, '山梨県'), (20, '長野県'), (21, '岐阜県'), (22, '静岡県'), (23, '愛知県'), (24, '三重県'), (25, '滋賀県'), (26, '京都府'), (27, '大阪府'), (28, '兵庫県'), (29, '奈良県'), (30, '和歌山県'), (31, '鳥取県'), (32, '島根県'), (33, '岡山県'), (34, '広島県'), (35, '山口県'), (36, '徳島県'), (37, '香川県'), (38, '愛媛県'), (39, '高知県'), (40, '福岡県'), (41, '佐賀県'), (42, '長崎県'), (43, '熊本県'), (44, '大分県'), (45, '宮崎県'), (46, '鹿児島県'), (47, '沖縄県')])),
                ('address', models.CharField(max_length=200)),
                ('gender_type', models.IntegerField(choices=[(1, '男性'), (2, '女性'), (3, '無回答')])),
                ('blood_type', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'O'), (4, 'AB')])),
                ('home_phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('cell_phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=13)),
                ('emergency_contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_name', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
                ('hitococo_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_member_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_member_plan_id', to='plans.plan')),
                ('updated_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_member_updated_user_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_member_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEscapeRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, max_length=300, null=True)),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_escape_route_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_escape_route_plan_id', to='plans.plan')),
                ('updated_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_escape_route_updated_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCustomGear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('sort_index', models.IntegerField()),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_customGear_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_customGear_gear_id', to='gears.gear')),
                ('updated_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_customGear_updated_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_plan_id', to='plans.plan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
