# Generated by Django 3.1.2 on 2020-10-27 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planroutedetail',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_detail_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planroutedetail',
            name='plan_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_detail_plan_route', to='plans.planroute'),
        ),
        migrations.AddField(
            model_name='planroutedetail',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_detail_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planroute',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planroute',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_plan', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='planroute',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_route_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planmember',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_member_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planmember',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_member_plan', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='planmember',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_member_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_member_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plangear',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_gear_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plangear',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_gear_plan', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='plangear',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_gear_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planescaperoute',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_escape_route_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planescaperoute',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_escape_route_plan', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='planescaperoute',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_escape_route_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plancustomgear',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_custom_gear_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plancustomgear',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_custom_gear_plan', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='plancustomgear',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_custom_gear_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_plan', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'plan')},
        ),
    ]
