# Generated by Django 3.1.2 on 2020-10-31 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20201027_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='water_liters',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
