# Generated by Django 3.1.2 on 2020-11-23 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0002_auto_20201027_2103'),
        ('plans', '0004_auto_20201031_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='plangear',
            name='gear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_gear_gear', to='gears.gear'),
        ),
    ]
