# Generated by Django 3.1.2 on 2020-10-17 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50)),
                ('purpose_type', models.IntegerField(choices=[(1, '登山'), (2, '登山（積雪期）'), (3, '登山（残雪期）'), (4, 'ハイキング'), (5, 'トレイルランニング'), (6, 'クライミング'), (7, 'アルパインクライミング'), (8, '沢登り'), (9, 'BCスキー'), (10, 'BCスノーボード'), (11, 'その他')])),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('has_rain_wear', models.BooleanField(default=True)),
                ('has_winter_clothing', models.BooleanField(default=True)),
                ('has_map', models.BooleanField(default=True)),
                ('has_compass', models.BooleanField(default=True)),
                ('has_headlamp', models.BooleanField(default=True)),
                ('has_mobile_phone', models.BooleanField(default=True)),
                ('has_spare_battery', models.BooleanField(default=True)),
                ('has_first_aid_kit', models.BooleanField(default=True)),
                ('has_emergency_tent', models.BooleanField(default=True)),
                ('has_transceiver', models.BooleanField(default=False)),
                ('call_sign', models.CharField(blank=True, max_length=50, null=True)),
                ('has_radio', models.BooleanField(default=False)),
                ('has_tent', models.BooleanField(default=False)),
                ('has_sleeping_bag', models.BooleanField(default=False)),
                ('has_stove', models.BooleanField(default=False)),
                ('has_helmet', models.BooleanField(default=False)),
                ('has_climbing_rope', models.BooleanField(default=False)),
                ('has_climbing_gear', models.BooleanField(default=False)),
                ('has_crampons', models.BooleanField(default=False)),
                ('has_ice_axe', models.BooleanField(default=False)),
                ('has_shovel', models.BooleanField(default=False)),
                ('has_beacon', models.BooleanField(default=False)),
                ('has_probe', models.BooleanField(default=False)),
                ('has_snow_saw', models.BooleanField(default=False)),
                ('has_riding_gear', models.BooleanField(default=False)),
                ('riding_type', models.IntegerField(blank=True, choices=[(1, 'スキー'), (2, 'スノーボード'), (3, 'スプリットボード'), (4, '雪板'), (5, 'その他')], null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomGear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('sort_index', models.IntegerField()),
                ('gear_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_gear_gear_id', to='gears.gear')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_gear_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
