# Generated by Django 3.1.2 on 2020-10-24 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gears', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customgear',
            name='gear_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_gear_gear_id', to='gears.gear'),
        ),
        migrations.AddField(
            model_name='customgear',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_gear_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
